[package]
name = "show-mm"
version = "0.1.0"
authors = ["Terrence Cole <terrence.d.cole@gmail.com>"]
edition = "2018"

[dependencies]
failure = "^ 0.1.2"
image = "^ 0.21"
log = "^ 0.4"
nalgebra = "^ 0.18"
simplelog = "^ 0.5"
structopt = "^ 0.2"
asset = { path = "../../libs/asset" }
camera = { path = "../../libs/render-shared/common/camera" }
gpu = { path = "../../libs/render-wgpu/common/gpu" }
input = { package = "input-wgpu", path = "../../libs/render-wgpu/common/input" }
t2_buffer = { package = "t2_buffer-wgpu", path = "../../libs/render-wgpu/buffer/t2_buffer" }
t2_terrain = { package = "t2_terrain-wgpu", path = "../../libs/render-wgpu/render_pass/t2_terrain" }
lay = { path = "../../libs/lay" }
lib = { path = "../../libs/lib" }
mm = { path = "../../libs/mm" }
omnilib = { path = "../../libs/omnilib" }
pic = { path = "../../libs/pic" }
pal = { path = "../../libs/pal" }
t2 = { path = "../../libs/t2" }
text = { path = "../../libs/render-vulkano/draw/text" }
xt = { path = "../../libs/xt" }
window = { path = "../../libs/render-vulkano/common/window" }
